apiVersion: apps/v1
kind: Deployment
metadata:
  name: vsffrwrw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vsffrwrw
  template:
    metadata:
      labels:
        app: vsffrwrw
    spec:
      containers:
      - image: okteto.dev/vsffrwrw:latest
        name: vsffrwrw
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "ebfd9fac-99c1-4b3d-ac96-2f041492782e"
        - name: Vless_Path
          value: "/ftcddggguysd"
        - name: Vmess_UUID
          value: "ebfd9fac-99c1-4b3d-ac96-2f041492782e"
        - name: Vmess_Path
          value: "/srtyhtrgrkjgyv"
        - name: Share_Path
          value: "/v2link"
